import axios from 'axios';
import { API_BASE_URL } from '@/data/services/apiConfig/apiContants';

/**
 * Uploads a file directly to AWS S3 using a presigned URL generated by our backend.
 * @param file The File object from an input element
 * @returns The final S3 URL of the uploaded file
 */
export const uploadToS3 = async (file: File): Promise<string> => {
  try {
    const filename = `${Date.now()}-${file.name.replace(/[^a-zA-Z0-9.-]/g, '_')}`;
    
    // 1. Get Presigned URL from Backend
    const presignedRes = await axios.post(`${API_BASE_URL}academy/s3/presigned-url`, {
      filename: filename,
      contentType: file.type,
    });
    
    // The backend should return the URL directly or in a specific format.
    // We assume the standard pattern where { url } is returned.
    const url = presignedRes.data?.data?.url || presignedRes.data?.url || presignedRes.data;
    
    if (!url || typeof url !== 'string') {
      console.error("Presigned URL response:", presignedRes.data);
      throw new Error("Failed to get presigned URL from backend.");
    }

    // 2. Upload file directly to S3
    await axios.put(url, file, {
      headers: {
        'Content-Type': file.type,
      },
    });

    // 3. Return the clean URL (without query parameters)
    const finalUrl = url.split('?')[0];
    return finalUrl;

  } catch (error) {
    console.error("Error uploading to S3:", error);
    throw error;
  }
};
