export const caseTypeOptions = [
    { value: "civil", label: "Civil" },
    { value: "criminal", label: "Criminal" },
    { value: "constitutional", label: "Constitutional" },
    { value: "corporate", label: "Corporate" },
    { value: "family", label: "Family" },
    { value: "consumer", label: "Consumer Disputes" },
    { value: "motor_accident", label: "Motor Accident Claims (MACT)" },
    { value: "cheque_bounce", label: "Cheque Bounce (NI Act 138)" },
    { value: "service", label: "Service Matters" },
    { value: "arbitration", label: "Arbitration" },
    { value: "ipr", label: "Intellectual Property (IPR)" },
    { value: "insolvency", label: "Insolvency (IBC)" },
    { value: "cyber_crime", label: "Cyber Crime" },
    { value: "tax", label: "Tax" },
    { value: "labor", label: "Labor" },
    { value: "property", label: "Property" },
    { value: "other", label: "Other" },
];
